# Generated by Django 4.2.1 on 2023-05-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_age_customuser_bio_customuser_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                blank=True,
                default="john doe",
                max_length=100,
                verbose_name="Name of User",
            ),
            preserve_default=False,
        ),
    ]
